services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
      - '1358:1358'
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,x-timestamp,X-Search-Id,X-Search-Click,X-Search-ClickPosition,X-Search-Conversion,X-User-Id,X-Forwarded-For
      - http.cors.allow-credentials=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - 'opensearch-data:/usr/share/opensearch/data'
    networks:
      - opensearch-net

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    user: root
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_DATA_PATH="/data"
    ports:
      - "4080:4080"
    volumes:
      - "zinc-data:/data"
    networks:
      - opensearch-net

  reactivesearch-api:
    container_name: rs-api
    image: appbaseio/reactivesearch-api:9.0.0.oss
    restart: always
    depends_on:
      - opensearch
      - zinc
    environment:
      - ES_CLUSTER_URL=http://opensearch:9200
      - ZINC_CLUSTER_URL=http://admin:Complexpass#123@zinc:4080
      - USERNAME=rs-admin-user
      - PASSWORD=rs-password
    volumes:
      - 'reactivesearch-data:/reactivesearch-data'
    ports:
      - '8000:8000'
    networks:
      - opensearch-net

  fluentbit:
    image: fluent/fluent-bit:4.0.8
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - reactivesearch-api
    restart: always
    volumes:
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro"
      - "./parser.conf:/fluent-bit/etc/parsers.conf:ro"
      - "reactivesearch-data:/reactivesearch-data"
      - "fluent-bit-state:/fluent-bit/state"
    networks:
      - opensearch-net


volumes:
  opensearch-data:
    driver: local
  reactivesearch-data:
    external: false
    name: reactivesearch-data
  zinc-data:
    external: false
    name: zinc-data
  fluent-bit-state:
    external: false
    name: fluent-bit-state

networks:
  opensearch-net:
    driver: bridge
